defaultPlacement: end
fieldLayouts:
  9a34241c-a29c-4700-9e64-2258aad61d85:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-03T14:45:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: dfe2ee32-eccf-4454-8c85-2eedd7575dbd
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 5998ce1a-8568-4419-afd0-42147ef351dd
        userCondition: null
    thumbFieldKey: null
handle: categories
name: Cat√©gories
siteSettings:
  5305348b-9508-42ef-ab8a-4896ff622bc6: # E2 Architecture | fr
    hasUrls: true
    template: categories/_categorie.twig
    uriFormat: 'categories/{slug}'
  e8e01ef6-f328-43cb-9d2c-4d8b31cfbaac: # E2 Architecture | nl
    hasUrls: true
    template: categories/_categorie.twig
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: 40583e15-9b42-4592-b751-d6aa1f18b937
