altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8788d604-b4ee-41c5-b9a1-9023feb53f97:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-03T13:54:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e83c5997-c43a-49fd-9af8-c6f935bc17f0
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 5980bd6f-17d5-4466-9336-7b56c7f4f131
        userCondition: null
    thumbFieldKey: null
fs: assets
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
