columnSuffix: null
handle: projectStyle
instructions: null
name: 'Type de vignette'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Vignette Verticale'
        -
          - value
          - vertical
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Vignette Horizontale Grande'
        -
          - value
          - horizontalBig
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Vignette Horizontale Petite'
        -
          - value
          - horizontalSmall
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
