defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8c6186ea-0e53-4618-8d7a-0ffe13ea19e8 # Projet
handle: projets
maxAuthors: 1
name: Projets
previewTargets:
  -
    label: 'Page d‘entrée primaire'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5305348b-9508-42ef-ab8a-4896ff622bc6: # E2 Architecture | fr
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry.twig
    uriFormat: 'projets/{slug}'
  e8e01ef6-f328-43cb-9d2c-4d8b31cfbaac: # E2 Architecture | nl
    enabledByDefault: true
    hasUrls: true
    template: projects\_entry.twig
    uriFormat: 'projecten/{slug}'
type: channel
